<?php

namespace ContainerJMT0cYj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BzqR5pwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BzqR5pw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BzqR5pw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dinosaureRepository' => ['privates', 'App\\Repository\\DinosaureRepository', 'getDinosaureRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dinosaureRepository' => 'App\\Repository\\DinosaureRepository',
            'entityManager' => '?',
        ]);
    }
}
