<?php

namespace ContainerJMT0cYj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdministrateurTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AdministrateurType' shared autowired service.
     *
     * @return \App\Form\AdministrateurType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AdministrateurType.php';

        return $container->privates['App\\Form\\AdministrateurType'] = new \App\Form\AdministrateurType();
    }
}
