<?php

namespace ContainerJMT0cYj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBiomeTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\BiomeType' shared autowired service.
     *
     * @return \App\Form\BiomeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/BiomeType.php';

        return $container->privates['App\\Form\\BiomeType'] = new \App\Form\BiomeType();
    }
}
