<?php

namespace ContainerJMT0cYj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrine_FixturesLoadCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'doctrine.fixtures_load_command' shared service.
     *
     * @return \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/src/Command/DoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Command/LoadDataFixturesDoctrineCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Loader/SymfonyFixturesLoader.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/FixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/SharedFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/AbstractFixture.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/ORMFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Fixture.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/AdministrateurFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/BiomeFixtures.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/data-fixtures/src/DependentFixtureInterface.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/ChambreFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/ClientFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/DateFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/DinosaureFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/EnclosFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/FormatBilletFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/FormatChambreFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/HoraireFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/HotelFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/JourFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/LouerHotelFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/OuvertureRestaurantFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/PayerBilletFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/ProduitFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/RemboursementBilletFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/RemboursementFixtures.php';
        include_once \dirname(__DIR__, 4).'/src/DataFixtures/RestaurantFixtures.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Purger/PurgerFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-fixtures-bundle/src/Purger/ORMPurgerFactory.php';

        $a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($container);

        $b = ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService'));
        $c = ($container->services['doctrine'] ?? self::getDoctrineService($container));

        $a->addFixtures([['fixture' => new \App\DataFixtures\AdministrateurFixtures($b), 'groups' => []], ['fixture' => new \App\DataFixtures\BiomeFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\ChambreFixtures($c), 'groups' => []], ['fixture' => new \App\DataFixtures\ClientFixtures($b), 'groups' => []], ['fixture' => new \App\DataFixtures\DateFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\DinosaureFixtures($c), 'groups' => []], ['fixture' => new \App\DataFixtures\EnclosFixtures($c), 'groups' => []], ['fixture' => new \App\DataFixtures\FormatBilletFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\FormatChambreFixtures($c), 'groups' => []], ['fixture' => new \App\DataFixtures\HoraireFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\HotelFixtures($c), 'groups' => []], ['fixture' => new \App\DataFixtures\JourFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\LouerHotelFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\OuvertureRestaurantFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\PayerBilletFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\ProduitFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\RemboursementBilletFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\RemboursementFixtures(), 'groups' => []], ['fixture' => new \App\DataFixtures\RestaurantFixtures($c), 'groups' => []]]);

        $container->privates['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, $c, ['default' => new \Doctrine\Bundle\FixturesBundle\Purger\ORMPurgerFactory()]);

        $instance->setName('doctrine:fixtures:load');

        return $instance;
    }
}
