name: CI Demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Afficher un message
        run: echo "Hello from GitHub Actions on Ubuntu!"

      - name: Lister les fichiers
        run: ls -la
