name: CI Demo

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Afficher un message
        run: echo "Hello from GitHub Actions on Ubuntu!"

      - name: Lister les fichiers
        run: ls -la
